# Generated by Django 6.0.6 on 2026-06-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAIZE', 'Maize'), ('GROUNDNUTS', 'Groundnuts'), ('GREEN_GRAMS', 'Green Grams'), ('MACADAMIA', 'Macadamia'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('subcounty', models.CharField(choices=[('MWATATE', 'Mwatate'), ('VOI', 'Voi'), ('WUNDANYI', 'Wundanyi'), ('TAVETA', 'Taveta')], max_length=50)),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crops', models.ManyToManyField(related_name='farmers', to='management.crop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
