# Generated by Django 6.0.6 on 2026-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_farmer_user_farmer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
