# Generated by Django 6.0.6 on 2026-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='expected_yield_per_acre',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='crop',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='crop',
            name='unit_measure',
            field=models.CharField(default='90kg bags', max_length=50),
        ),
    ]
