# Generated by Django 6.0.6 on 2026-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_backuplog_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
